name: Test Build

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test-build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: yarn
      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Build Project
        run: yarn build
