name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: yarn
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Build Project
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: lidofinance/github-pages-action@v1
        with:
          branch: gh-pages
          folder: build
